name: CI Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:      
    
      - name: Checkout code
        uses: actions/checkout@v3
     
      - name: Build Docker image
        run: docker build -t flask-app .

      - name: Run tests
        run: echo "Test"
